### ISSUE TITLE
Reflect setField error

### ISSUE THREAD

**Issue by 4lxprime** [4lxprime/gtml#2]
We'll need to fix the setField function which is using reflect for updating Elements struct fields with fieldName and fieldValue, but also including all child fields of the Basic Element field (which is a sruct that implement html global attributes). The thing is that we need to give this function the Element interface
here is the error that i get in the browser:

panic: reflect: call of reflect.Value.FieldByName on interface Value
<empty string>
goroutine 1 [running]:
reflect.flag.mustBe(...)
	C:/Program Files/Go/src/reflect/value.go:223
reflect.Value.FieldByName({0x11840, 0x40e080, 0x194}, {0x2696c, 0x5})
	C:/Program Files/Go/src/reflect/value.go:1345 +0x10
github.com/4lxprime/gtml/elements.setField({0x21320, 0x458000}, {0x2696c, 0x5}, {0xf520, 0x40e070})
	C:/Users/idalx/Documents/Git/agit/elements/utils.go:31 +0x3a
github.com/4lxprime/gtml/elements.elementImpl({0x21320, 0x458000}, {0x44ef88, 0x1, 0x1})
	C:/Users/idalx/Documents/Git/agit/elements/elements.go:15 +0x5
github.com/4lxprime/gtml/elements.Div(...)
	C:/Users/idalx/Documents/Git/agit/elements/elements.go:1630
main.App(0x40a048)
	C:/Users/idalx/Documents/Git/agit/example/app/main.go:19 +0x1d
main.main()
	C:/Users/idalx/Documents/Git/agit/example/app/main.go:72 +0xb

**Comment by 4lxprime** [comment]
this is fixed, i just had to use the Element interface as a ptr for element struct.
